<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
<!--        <TargetFrameworks>netstandard2.0;netstandard2.1;net8.0;net9.0;net10.0</TargetFrameworks>-->
        <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BouncyCastle.Cryptography" />
    </ItemGroup>

    <!-- 为 .NET Standard 2.0/2.1 添加所需的包 -->
    <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0' OR '$(TargetFramework)' == 'netstandard2.1'">
        <PackageReference Include="System.ComponentModel.Annotations"/>
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Resources\CryptoUtilCore.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>CryptoUtil.Core.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\CryptoUtilCore.en-us.resx">
        <DependentUpon>CryptoUtil.Core.resx</DependentUpon>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\CryptoUtilCore.zh-hans.resx">
        <DependentUpon>CryptoUtil.Core.resx</DependentUpon>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Resources\CryptoUtilCore.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>CryptoUtil.Core.resx</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
