//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crypto.Utils.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CryptoUtil_Core {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CryptoUtil_Core() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Crypto.Utils.Resources.CryptoUtil_Core", typeof(CryptoUtil_Core).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CertificatePolicy_None {
            get {
                return ResourceManager.GetString("CertificatePolicy_None", resourceCulture);
            }
        }
        
        internal static string CertificatePolicy_AnyPolicy {
            get {
                return ResourceManager.GetString("CertificatePolicy_AnyPolicy", resourceCulture);
            }
        }
        
        internal static string CertificatePolicy_DomainValidated {
            get {
                return ResourceManager.GetString("CertificatePolicy_DomainValidated", resourceCulture);
            }
        }
        
        internal static string CertificatePolicy_OrganizationValidated {
            get {
                return ResourceManager.GetString("CertificatePolicy_OrganizationValidated", resourceCulture);
            }
        }
        
        internal static string CertificatePolicy_ExtendedValidation {
            get {
                return ResourceManager.GetString("CertificatePolicy_ExtendedValidation", resourceCulture);
            }
        }
        
        internal static string CertificatePolicy_MicrosoftDocumentSigning {
            get {
                return ResourceManager.GetString("CertificatePolicy_MicrosoftDocumentSigning", resourceCulture);
            }
        }
        
        internal static string CrlReason_Unspecified {
            get {
                return ResourceManager.GetString("CrlReason_Unspecified", resourceCulture);
            }
        }
        
        internal static string CrlReason_KeyCompromise {
            get {
                return ResourceManager.GetString("CrlReason_KeyCompromise", resourceCulture);
            }
        }
        
        internal static string CrlReason_CACompromise {
            get {
                return ResourceManager.GetString("CrlReason_CACompromise", resourceCulture);
            }
        }
        
        internal static string CrlReason_AffiliationChanged {
            get {
                return ResourceManager.GetString("CrlReason_AffiliationChanged", resourceCulture);
            }
        }
        
        internal static string CrlReason_Superseded {
            get {
                return ResourceManager.GetString("CrlReason_Superseded", resourceCulture);
            }
        }
        
        internal static string CrlReason_CessationOfOperation {
            get {
                return ResourceManager.GetString("CrlReason_CessationOfOperation", resourceCulture);
            }
        }
        
        internal static string CrlReason_CertificateHold {
            get {
                return ResourceManager.GetString("CrlReason_CertificateHold", resourceCulture);
            }
        }
        
        internal static string CrlReason_RemoveFromCrl {
            get {
                return ResourceManager.GetString("CrlReason_RemoveFromCrl", resourceCulture);
            }
        }
        
        internal static string CrlReason_PrivilegeWithdrawn {
            get {
                return ResourceManager.GetString("CrlReason_PrivilegeWithdrawn", resourceCulture);
            }
        }
        
        internal static string CrlReason_AACompromise {
            get {
                return ResourceManager.GetString("CrlReason_AACompromise", resourceCulture);
            }
        }
        
        internal static string ExtendedKeyUsage_None {
            get {
                return ResourceManager.GetString("ExtendedKeyUsage_None", resourceCulture);
            }
        }
        
        internal static string ExtendedKeyUsage_ServerAuthentication {
            get {
                return ResourceManager.GetString("ExtendedKeyUsage_ServerAuthentication", resourceCulture);
            }
        }
        
        internal static string ExtendedKeyUsage_ClientAuthentication {
            get {
                return ResourceManager.GetString("ExtendedKeyUsage_ClientAuthentication", resourceCulture);
            }
        }
        
        internal static string ExtendedKeyUsage_CodeSigning {
            get {
                return ResourceManager.GetString("ExtendedKeyUsage_CodeSigning", resourceCulture);
            }
        }
        
        internal static string ExtendedKeyUsage_EmailProtection {
            get {
                return ResourceManager.GetString("ExtendedKeyUsage_EmailProtection", resourceCulture);
            }
        }
        
        internal static string ExtendedKeyUsage_IpsecEndSystem {
            get {
                return ResourceManager.GetString("ExtendedKeyUsage_IpsecEndSystem", resourceCulture);
            }
        }
        
        internal static string ExtendedKeyUsage_IpsecTunnel {
            get {
                return ResourceManager.GetString("ExtendedKeyUsage_IpsecTunnel", resourceCulture);
            }
        }
        
        internal static string ExtendedKeyUsage_IpsecUser {
            get {
                return ResourceManager.GetString("ExtendedKeyUsage_IpsecUser", resourceCulture);
            }
        }
        
        internal static string ExtendedKeyUsage_TimeStamping {
            get {
                return ResourceManager.GetString("ExtendedKeyUsage_TimeStamping", resourceCulture);
            }
        }
        
        internal static string ExtendedKeyUsage_OcspSigning {
            get {
                return ResourceManager.GetString("ExtendedKeyUsage_OcspSigning", resourceCulture);
            }
        }
        
        internal static string ExtendedKeyUsage_Dvcs {
            get {
                return ResourceManager.GetString("ExtendedKeyUsage_Dvcs", resourceCulture);
            }
        }
        
        internal static string ExtendedKeyUsage_SbgpCertificate {
            get {
                return ResourceManager.GetString("ExtendedKeyUsage_SbgpCertificate", resourceCulture);
            }
        }
        
        internal static string ExtendedKeyUsage_EapOverPpp {
            get {
                return ResourceManager.GetString("ExtendedKeyUsage_EapOverPpp", resourceCulture);
            }
        }
        
        internal static string ExtendedKeyUsage_EapOverLan {
            get {
                return ResourceManager.GetString("ExtendedKeyUsage_EapOverLan", resourceCulture);
            }
        }
        
        internal static string ExtendedKeyUsage_SshClient {
            get {
                return ResourceManager.GetString("ExtendedKeyUsage_SshClient", resourceCulture);
            }
        }
        
        internal static string ExtendedKeyUsage_SshServer {
            get {
                return ResourceManager.GetString("ExtendedKeyUsage_SshServer", resourceCulture);
            }
        }
        
        internal static string ExtendedKeyUsage_DocumentSigning {
            get {
                return ResourceManager.GetString("ExtendedKeyUsage_DocumentSigning", resourceCulture);
            }
        }
        
        internal static string ExtendedKeyUsage_AnyPurpose {
            get {
                return ResourceManager.GetString("ExtendedKeyUsage_AnyPurpose", resourceCulture);
            }
        }
        
        internal static string ExtendedKeyUsage_SmartCardLogon {
            get {
                return ResourceManager.GetString("ExtendedKeyUsage_SmartCardLogon", resourceCulture);
            }
        }
        
        internal static string GeneralNameType_Unknown {
            get {
                return ResourceManager.GetString("GeneralNameType_Unknown", resourceCulture);
            }
        }
        
        internal static string GeneralNameType_OtherName {
            get {
                return ResourceManager.GetString("GeneralNameType_OtherName", resourceCulture);
            }
        }
        
        internal static string GeneralNameType_Rfc822Name {
            get {
                return ResourceManager.GetString("GeneralNameType_Rfc822Name", resourceCulture);
            }
        }
        
        internal static string GeneralNameType_DnsName {
            get {
                return ResourceManager.GetString("GeneralNameType_DnsName", resourceCulture);
            }
        }
        
        internal static string GeneralNameType_X400Address {
            get {
                return ResourceManager.GetString("GeneralNameType_X400Address", resourceCulture);
            }
        }
        
        internal static string GeneralNameType_DirectoryName {
            get {
                return ResourceManager.GetString("GeneralNameType_DirectoryName", resourceCulture);
            }
        }
        
        internal static string GeneralNameType_EdiPartyName {
            get {
                return ResourceManager.GetString("GeneralNameType_EdiPartyName", resourceCulture);
            }
        }
        
        internal static string GeneralNameType_UniformResourceIdentifier {
            get {
                return ResourceManager.GetString("GeneralNameType_UniformResourceIdentifier", resourceCulture);
            }
        }
        
        internal static string GeneralNameType_IPAddress {
            get {
                return ResourceManager.GetString("GeneralNameType_IPAddress", resourceCulture);
            }
        }
        
        internal static string GeneralNameType_RegisteredID {
            get {
                return ResourceManager.GetString("GeneralNameType_RegisteredID", resourceCulture);
            }
        }
        
        internal static string KeyUsage_None {
            get {
                return ResourceManager.GetString("KeyUsage_None", resourceCulture);
            }
        }
        
        internal static string KeyUsage_DigitalSignature {
            get {
                return ResourceManager.GetString("KeyUsage_DigitalSignature", resourceCulture);
            }
        }
        
        internal static string KeyUsage_NonRepudiation {
            get {
                return ResourceManager.GetString("KeyUsage_NonRepudiation", resourceCulture);
            }
        }
        
        internal static string KeyUsage_KeyEncipherment {
            get {
                return ResourceManager.GetString("KeyUsage_KeyEncipherment", resourceCulture);
            }
        }
        
        internal static string KeyUsage_DataEncipherment {
            get {
                return ResourceManager.GetString("KeyUsage_DataEncipherment", resourceCulture);
            }
        }
        
        internal static string KeyUsage_KeyAgreement {
            get {
                return ResourceManager.GetString("KeyUsage_KeyAgreement", resourceCulture);
            }
        }
        
        internal static string KeyUsage_KeyCertSign {
            get {
                return ResourceManager.GetString("KeyUsage_KeyCertSign", resourceCulture);
            }
        }
        
        internal static string KeyUsage_CrlSign {
            get {
                return ResourceManager.GetString("KeyUsage_CrlSign", resourceCulture);
            }
        }
        
        internal static string KeyUsage_EncipherOnly {
            get {
                return ResourceManager.GetString("KeyUsage_EncipherOnly", resourceCulture);
            }
        }
        
        internal static string KeyUsage_DecipherOnly {
            get {
                return ResourceManager.GetString("KeyUsage_DecipherOnly", resourceCulture);
            }
        }
        
        internal static string Error_CannotParsePemKey {
            get {
                return ResourceManager.GetString("Error_CannotParsePemKey", resourceCulture);
            }
        }
        
        internal static string Error_InvalidKeyInPem {
            get {
                return ResourceManager.GetString("Error_InvalidKeyInPem", resourceCulture);
            }
        }
        
        internal static string Error_CannotParsePrivateKeyFromDer {
            get {
                return ResourceManager.GetString("Error_CannotParsePrivateKeyFromDer", resourceCulture);
            }
        }
        
        internal static string Error_CannotParsePrivateKeyFromPem {
            get {
                return ResourceManager.GetString("Error_CannotParsePrivateKeyFromPem", resourceCulture);
            }
        }
        
        internal static string Error_InvalidPrivateKeyInPem {
            get {
                return ResourceManager.GetString("Error_InvalidPrivateKeyInPem", resourceCulture);
            }
        }
        
        internal static string Error_CannotParsePublicKeyFromPem {
            get {
                return ResourceManager.GetString("Error_CannotParsePublicKeyFromPem", resourceCulture);
            }
        }
        
        internal static string Error_InvalidPublicKeyInPem {
            get {
                return ResourceManager.GetString("Error_InvalidPublicKeyInPem", resourceCulture);
            }
        }
        
        internal static string Error_CannotParseCsrFromPem {
            get {
                return ResourceManager.GetString("Error_CannotParseCsrFromPem", resourceCulture);
            }
        }
        
        internal static string Error_CannotParseCrlFromPem {
            get {
                return ResourceManager.GetString("Error_CannotParseCrlFromPem", resourceCulture);
            }
        }
        
        internal static string Error_CannotParseCertificateFromPem {
            get {
                return ResourceManager.GetString("Error_CannotParseCertificateFromPem", resourceCulture);
            }
        }
        
        internal static string Error_KeyNotPrivate {
            get {
                return ResourceManager.GetString("Error_KeyNotPrivate", resourceCulture);
            }
        }
        
        internal static string Error_UnknownEcCurve {
            get {
                return ResourceManager.GetString("Error_UnknownEcCurve", resourceCulture);
            }
        }
        
        internal static string Error_KeyNotPublic {
            get {
                return ResourceManager.GetString("Error_KeyNotPublic", resourceCulture);
            }
        }
        
        internal static string Error_UnsupportedHashAlgorithm {
            get {
                return ResourceManager.GetString("Error_UnsupportedHashAlgorithm", resourceCulture);
            }
        }
        
        internal static string Error_InputDataCannotBeEmpty {
            get {
                return ResourceManager.GetString("Error_InputDataCannotBeEmpty", resourceCulture);
            }
        }
        
        internal static string Error_DestinationBufferTooShort {
            get {
                return ResourceManager.GetString("Error_DestinationBufferTooShort", resourceCulture);
            }
        }
        
        internal static string Error_StreamDoesNotSupportReading {
            get {
                return ResourceManager.GetString("Error_StreamDoesNotSupportReading", resourceCulture);
            }
        }
        
        internal static string Error_InvalidKeySize {
            get {
                return ResourceManager.GetString("Error_InvalidKeySize", resourceCulture);
            }
        }
        
        internal static string Error_InvalidIVSize {
            get {
                return ResourceManager.GetString("Error_InvalidIVSize", resourceCulture);
            }
        }
        
        internal static string Error_InvalidCiphertextLength {
            get {
                return ResourceManager.GetString("Error_InvalidCiphertextLength", resourceCulture);
            }
        }
        
        internal static string Error_InvalidC1PointFormat {
            get {
                return ResourceManager.GetString("Error_InvalidC1PointFormat", resourceCulture);
            }
        }
        
        internal static string Error_InvalidAsn1SM2CiphertextStructure {
            get {
                return ResourceManager.GetString("Error_InvalidAsn1SM2CiphertextStructure", resourceCulture);
            }
        }
        
        internal static string Error_InputBufferTooSmall {
            get {
                return ResourceManager.GetString("Error_InputBufferTooSmall", resourceCulture);
            }
        }
        
        internal static string Error_OutputBufferTooSmall {
            get {
                return ResourceManager.GetString("Error_OutputBufferTooSmall", resourceCulture);
            }
        }
        
        internal static string Error_SignatureCannotBeEmpty {
            get {
                return ResourceManager.GetString("Error_SignatureCannotBeEmpty", resourceCulture);
            }
        }
        
        internal static string Error_InvalidCipherMode {
            get {
                return ResourceManager.GetString("Error_InvalidCipherMode", resourceCulture);
            }
        }
        
        internal static string Error_InvalidPaddingMode {
            get {
                return ResourceManager.GetString("Error_InvalidPaddingMode", resourceCulture);
            }
        }
        
        internal static string Error_PublicKeyNotInitialized {
            get {
                return ResourceManager.GetString("Error_PublicKeyNotInitialized", resourceCulture);
            }
        }
        
        internal static string Error_PrivateKeyNotInitialized {
            get {
                return ResourceManager.GetString("Error_PrivateKeyNotInitialized", resourceCulture);
            }
        }
        
        internal static string Error_NotSm2PublicKey {
            get {
                return ResourceManager.GetString("Error_NotSm2PublicKey", resourceCulture);
            }
        }
        
        internal static string Error_NotSm2PrivateKey {
            get {
                return ResourceManager.GetString("Error_NotSm2PrivateKey", resourceCulture);
            }
        }
        
        internal static string Error_PrivateKeyNotAvailableForSigning {
            get {
                return ResourceManager.GetString("Error_PrivateKeyNotAvailableForSigning", resourceCulture);
            }
        }
        
        internal static string Error_PublicKeyNotAvailableForVerification {
            get {
                return ResourceManager.GetString("Error_PublicKeyNotAvailableForVerification", resourceCulture);
            }
        }
        
        internal static string Error_PublicKeyNotAvailableForEncryption {
            get {
                return ResourceManager.GetString("Error_PublicKeyNotAvailableForEncryption", resourceCulture);
            }
        }
        
        internal static string Error_PrivateKeyNotAvailableForDecryption {
            get {
                return ResourceManager.GetString("Error_PrivateKeyNotAvailableForDecryption", resourceCulture);
            }
        }
        
        internal static string Error_CipherModeNotSupported {
            get {
                return ResourceManager.GetString("Error_CipherModeNotSupported", resourceCulture);
            }
        }
        
        internal static string Error_PaddingModeNotSupported {
            get {
                return ResourceManager.GetString("Error_PaddingModeNotSupported", resourceCulture);
            }
        }
        
        internal static string Error_KeyNotSet {
            get {
                return ResourceManager.GetString("Error_KeyNotSet", resourceCulture);
            }
        }
        
        internal static string Error_CryptographicOperationFailed {
            get {
                return ResourceManager.GetString("Error_CryptographicOperationFailed", resourceCulture);
            }
        }
        
        internal static string Error_CannotExtractPublicKeyFromPrivateKeyType {
            get {
                return ResourceManager.GetString("Error_CannotExtractPublicKeyFromPrivateKeyType", resourceCulture);
            }
        }
        
        internal static string Error_UnsupportedPrivateKeyType {
            get {
                return ResourceManager.GetString("Error_UnsupportedPrivateKeyType", resourceCulture);
            }
        }
    }
}
