//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crypto.Utils.Resources
{
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnumResources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumResources()
        {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crypto.Utils.Resources.EnumResources", typeof(EnumResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 任何策略 的本地化字符串。
        /// </summary>
        internal static string CertificatePolicy_AnyPolicy
        {
            get
            {
                return ResourceManager.GetString("CertificatePolicy_AnyPolicy", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 域名验证 (DV) 的本地化字符串。
        /// </summary>
        internal static string CertificatePolicy_DomainValidated
        {
            get
            {
                return ResourceManager.GetString("CertificatePolicy_DomainValidated", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 扩展验证 (EV) 的本地化字符串。
        /// </summary>
        internal static string CertificatePolicy_ExtendedValidation
        {
            get
            {
                return ResourceManager.GetString("CertificatePolicy_ExtendedValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Microsoft 文档签名 的本地化字符串。
        /// </summary>
        internal static string CertificatePolicy_MicrosoftDocumentSigning
        {
            get
            {
                return ResourceManager.GetString("CertificatePolicy_MicrosoftDocumentSigning", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 未指定策略 的本地化字符串。
        /// </summary>
        internal static string CertificatePolicy_None
        {
            get
            {
                return ResourceManager.GetString("CertificatePolicy_None", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 组织验证 (OV) 的本地化字符串。
        /// </summary>
        internal static string CertificatePolicy_OrganizationValidated
        {
            get
            {
                return ResourceManager.GetString("CertificatePolicy_OrganizationValidated", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 AA 泄露 的本地化字符串。
        /// </summary>
        internal static string CrlReason_AACompromise
        {
            get
            {
                return ResourceManager.GetString("CrlReason_AACompromise", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 从属关系变更 的本地化字符串。
        /// </summary>
        internal static string CrlReason_AffiliationChanged
        {
            get
            {
                return ResourceManager.GetString("CrlReason_AffiliationChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 CA 泄露 的本地化字符串。
        /// </summary>
        internal static string CrlReason_CACompromise
        {
            get
            {
                return ResourceManager.GetString("CrlReason_CACompromise", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 证书挂起 的本地化字符串。
        /// </summary>
        internal static string CrlReason_CertificateHold
        {
            get
            {
                return ResourceManager.GetString("CrlReason_CertificateHold", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 停止运营 的本地化字符串。
        /// </summary>
        internal static string CrlReason_CessationOfOperation
        {
            get
            {
                return ResourceManager.GetString("CrlReason_CessationOfOperation", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 密钥泄露 的本地化字符串。
        /// </summary>
        internal static string CrlReason_KeyCompromise
        {
            get
            {
                return ResourceManager.GetString("CrlReason_KeyCompromise", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 特权撤销 的本地化字符串。
        /// </summary>
        internal static string CrlReason_PrivilegeWithdrawn
        {
            get
            {
                return ResourceManager.GetString("CrlReason_PrivilegeWithdrawn", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 从 CRL 中移除 的本地化字符串。
        /// </summary>
        internal static string CrlReason_RemoveFromCrl
        {
            get
            {
                return ResourceManager.GetString("CrlReason_RemoveFromCrl", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 被取代 的本地化字符串。
        /// </summary>
        internal static string CrlReason_Superseded
        {
            get
            {
                return ResourceManager.GetString("CrlReason_Superseded", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 未指定原因 的本地化字符串。
        /// </summary>
        internal static string CrlReason_Unspecified
        {
            get
            {
                return ResourceManager.GetString("CrlReason_Unspecified", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 任何目的 的本地化字符串。
        /// </summary>
        internal static string ExtendedKeyUsage_AnyPurpose
        {
            get
            {
                return ResourceManager.GetString("ExtendedKeyUsage_AnyPurpose", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 客户端身份验证 的本地化字符串。
        /// </summary>
        internal static string ExtendedKeyUsage_ClientAuthentication
        {
            get
            {
                return ResourceManager.GetString("ExtendedKeyUsage_ClientAuthentication", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 代码签名 的本地化字符串。
        /// </summary>
        internal static string ExtendedKeyUsage_CodeSigning
        {
            get
            {
                return ResourceManager.GetString("ExtendedKeyUsage_CodeSigning", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 文档签名 的本地化字符串。
        /// </summary>
        internal static string ExtendedKeyUsage_DocumentSigning
        {
            get
            {
                return ResourceManager.GetString("ExtendedKeyUsage_DocumentSigning", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 数据验证和认证服务 的本地化字符串。
        /// </summary>
        internal static string ExtendedKeyUsage_Dvcs
        {
            get
            {
                return ResourceManager.GetString("ExtendedKeyUsage_Dvcs", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 LAN 上的 EAP 的本地化字符串。
        /// </summary>
        internal static string ExtendedKeyUsage_EapOverLan
        {
            get
            {
                return ResourceManager.GetString("ExtendedKeyUsage_EapOverLan", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 PPP 上的 EAP 的本地化字符串。
        /// </summary>
        internal static string ExtendedKeyUsage_EapOverPpp
        {
            get
            {
                return ResourceManager.GetString("ExtendedKeyUsage_EapOverPpp", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 电子邮件保护 的本地化字符串。
        /// </summary>
        internal static string ExtendedKeyUsage_EmailProtection
        {
            get
            {
                return ResourceManager.GetString("ExtendedKeyUsage_EmailProtection", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 IPsec 终端系统 的本地化字符串。
        /// </summary>
        internal static string ExtendedKeyUsage_IpsecEndSystem
        {
            get
            {
                return ResourceManager.GetString("ExtendedKeyUsage_IpsecEndSystem", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 IPsec 隧道 的本地化字符串。
        /// </summary>
        internal static string ExtendedKeyUsage_IpsecTunnel
        {
            get
            {
                return ResourceManager.GetString("ExtendedKeyUsage_IpsecTunnel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 IPsec 用户 的本地化字符串。
        /// </summary>
        internal static string ExtendedKeyUsage_IpsecUser
        {
            get
            {
                return ResourceManager.GetString("ExtendedKeyUsage_IpsecUser", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        internal static string ExtendedKeyUsage_None
        {
            get
            {
                return ResourceManager.GetString("ExtendedKeyUsage_None", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 OCSP 签名 的本地化字符串。
        /// </summary>
        internal static string ExtendedKeyUsage_OcspSigning
        {
            get
            {
                return ResourceManager.GetString("ExtendedKeyUsage_OcspSigning", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 安全 BGP 证书 的本地化字符串。
        /// </summary>
        internal static string ExtendedKeyUsage_SbgpCertificate
        {
            get
            {
                return ResourceManager.GetString("ExtendedKeyUsage_SbgpCertificate", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 服务器身份验证 的本地化字符串。
        /// </summary>
        internal static string ExtendedKeyUsage_ServerAuthentication
        {
            get
            {
                return ResourceManager.GetString("ExtendedKeyUsage_ServerAuthentication", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 智能卡登录 的本地化字符串。
        /// </summary>
        internal static string ExtendedKeyUsage_SmartCardLogon
        {
            get
            {
                return ResourceManager.GetString("ExtendedKeyUsage_SmartCardLogon", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 SSH 客户端 的本地化字符串。
        /// </summary>
        internal static string ExtendedKeyUsage_SshClient
        {
            get
            {
                return ResourceManager.GetString("ExtendedKeyUsage_SshClient", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 SSH 服务器 的本地化字符串。
        /// </summary>
        internal static string ExtendedKeyUsage_SshServer
        {
            get
            {
                return ResourceManager.GetString("ExtendedKeyUsage_SshServer", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 时间戳 的本地化字符串。
        /// </summary>
        internal static string ExtendedKeyUsage_TimeStamping
        {
            get
            {
                return ResourceManager.GetString("ExtendedKeyUsage_TimeStamping", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 目录名称 的本地化字符串。
        /// </summary>
        internal static string GeneralNameType_DirectoryName
        {
            get
            {
                return ResourceManager.GetString("GeneralNameType_DirectoryName", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 DNS 名称 的本地化字符串。
        /// </summary>
        internal static string GeneralNameType_DnsName
        {
            get
            {
                return ResourceManager.GetString("GeneralNameType_DnsName", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 EDI 方名称 的本地化字符串。
        /// </summary>
        internal static string GeneralNameType_EdiPartyName
        {
            get
            {
                return ResourceManager.GetString("GeneralNameType_EdiPartyName", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 IP 地址 的本地化字符串。
        /// </summary>
        internal static string GeneralNameType_IPAddress
        {
            get
            {
                return ResourceManager.GetString("GeneralNameType_IPAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 其他名称 的本地化字符串。
        /// </summary>
        internal static string GeneralNameType_OtherName
        {
            get
            {
                return ResourceManager.GetString("GeneralNameType_OtherName", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 注册 ID 的本地化字符串。
        /// </summary>
        internal static string GeneralNameType_RegisteredID
        {
            get
            {
                return ResourceManager.GetString("GeneralNameType_RegisteredID", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 RFC 822 名称 的本地化字符串。
        /// </summary>
        internal static string GeneralNameType_Rfc822Name
        {
            get
            {
                return ResourceManager.GetString("GeneralNameType_Rfc822Name", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 统一资源标识符 的本地化字符串。
        /// </summary>
        internal static string GeneralNameType_UniformResourceIdentifier
        {
            get
            {
                return ResourceManager.GetString("GeneralNameType_UniformResourceIdentifier", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 未知类型 的本地化字符串。
        /// </summary>
        internal static string GeneralNameType_Unknown
        {
            get
            {
                return ResourceManager.GetString("GeneralNameType_Unknown", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 X.400 地址 的本地化字符串。
        /// </summary>
        internal static string GeneralNameType_X400Address
        {
            get
            {
                return ResourceManager.GetString("GeneralNameType_X400Address", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 CRL 签名 的本地化字符串。
        /// </summary>
        internal static string KeyUsage_CrlSign
        {
            get
            {
                return ResourceManager.GetString("KeyUsage_CrlSign", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 数据加密 的本地化字符串。
        /// </summary>
        internal static string KeyUsage_DataEncipherment
        {
            get
            {
                return ResourceManager.GetString("KeyUsage_DataEncipherment", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 仅用于解密 的本地化字符串。
        /// </summary>
        internal static string KeyUsage_DecipherOnly
        {
            get
            {
                return ResourceManager.GetString("KeyUsage_DecipherOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 数字签名 的本地化字符串。
        /// </summary>
        internal static string KeyUsage_DigitalSignature
        {
            get
            {
                return ResourceManager.GetString("KeyUsage_DigitalSignature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 仅用于加密 的本地化字符串。
        /// </summary>
        internal static string KeyUsage_EncipherOnly
        {
            get
            {
                return ResourceManager.GetString("KeyUsage_EncipherOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 密钥协商 的本地化字符串。
        /// </summary>
        internal static string KeyUsage_KeyAgreement
        {
            get
            {
                return ResourceManager.GetString("KeyUsage_KeyAgreement", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 证书签名 的本地化字符串。
        /// </summary>
        internal static string KeyUsage_KeyCertSign
        {
            get
            {
                return ResourceManager.GetString("KeyUsage_KeyCertSign", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 密钥加密 的本地化字符串。
        /// </summary>
        internal static string KeyUsage_KeyEncipherment
        {
            get
            {
                return ResourceManager.GetString("KeyUsage_KeyEncipherment", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        internal static string KeyUsage_None
        {
            get
            {
                return ResourceManager.GetString("KeyUsage_None", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 不可否认性 的本地化字符串。
        /// </summary>
        internal static string KeyUsage_NonRepudiation
        {
            get
            {
                return ResourceManager.GetString("KeyUsage_NonRepudiation", resourceCulture);
            }
        }
    }
}
