<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2"/>
        <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.6.2"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Crypto.Utils.Core\Crypto.Utils.Core.csproj"/>
    </ItemGroup>

</Project>

